site_name: Messy Notes...
theme:
    name: material
    
nav:
  - 首页: 'index.md'
  # - PA:
    # - PA0: ysyx/pa/pa0/pa0.md
    # - PA1: ysyx/pa/pa1/pa1.md
    # - PA2: ysyx/pa/pa2/pa2.md
    # - PA3: ysyx/pa/pa3/pa3.md
    # - PA4: ysyx/pa/pa4/pa4.md
    # - Linux Porting: ysyx/pa/Linux_porting/porting.md
    # - C Macro: ysyx/pa/c_marco/macro.md
    # - Summary: ysyx/pa/summary/summary.md
  - ysyx:
    - Digital Circuit: ysyx\digital-circuit/digital circuit.md